// Seed data imported from seeds/*.md files
// Generated by generate-seed-docs.cjs

export const SEED_SPACING = {
  "Bupleurum Green Gold": { spacing: 15, rows: null },
  "Cress Attraxa": { spacing: 20, rows: null },
  "Sedum Spirit": { spacing: null, rows: null },
  "Lavender": { spacing: 45, rows: null },
  "Orach Ruby Gold": { spacing: 60, rows: null },
  "Utrecht Blue Millet & Wheat": { spacing: 15, rows: null },
  "Bells of Ireland": { spacing: 30, rows: null },
  "Zinnia Lilliput Rose": { spacing: 22, rows: null }, // 20-25cm -> average
  "Zinnia Zinderella Lilac": { spacing: 27, rows: null }, // 25-30cm -> average
  "Zinnia Molotov Mix": { spacing: 27, rows: null },
  "Zinnia Peaches + Cream": { spacing: 27, rows: null },
  "Zinnia Queeny Lime Orange": { spacing: 30, rows: null },
  "Zinnia Queeny Lime Blotch": { spacing: 30, rows: null },
  "Zinnia Queeny Lemon Peach": { spacing: 30, rows: null },
  "Pansy Chianti Shades F1": { spacing: 20, rows: null },
  "Pansy Inspire True Blue": { spacing: 20, rows: null },
  "Pansy Super Swiss Giants": { spacing: 20, rows: null },
  "French Marigold Petite Yellow": { spacing: 20, rows: null },
  "Edelweiss": { spacing: null, rows: null },
  "Nigella Miss Jekyll": { spacing: 15, rows: null },
  "Nigella Persian Jewels": { spacing: 15, rows: null },
  "Nigella Cramer's Plum": { spacing: 15, rows: null },
  "Love in a Mist Cramer's Plum Loco": { spacing: 15, rows: null },
  "Ozark Sundrop": { spacing: null, rows: null },
  "Lupin Pink Fairy": { spacing: null, rows: null },
  "Kiwi Blue Honeywort": { spacing: 25, rows: null },
  "Caramel Rudbeckia": { spacing: 30, rows: null },
  "Callistephus Classic Salmon Rose": { spacing: 25, rows: null },
  "Statice Art Shades Mixed": { spacing: 25, rows: null },
  "Strawflower Mixed Colours": { spacing: 25, rows: null },
  "Pyretheum Painted Daisy": { spacing: 30, rows: null },
  "Cornflower Classic Romantic": { spacing: 15, rows: null },
  "Cornflower Blue Diadem": { spacing: 15, rows: null },
  "African Marigold Glow Up Gold": { spacing: 45, rows: null },
  "Blue Glitter Sea Holly": { spacing: 30, rows: null },
  "Snapdragon Rocket Hybrids": { spacing: 25, rows: null },
  "Snapdragon Panorama Mixed": { spacing: 25, rows: null },
  "Lupins Russells Red": { spacing: 45, rows: null },
  "Poppy Hens & Chicks": { spacing: 22, rows: null }, // 20-25cm -> average
  "Shirley Poppy Pastel Doubles": { spacing: 15, rows: null },
  "Red Breadseed Poppy": { spacing: 15, rows: null },
  "Wulff Dill": { spacing: 30, rows: null },
  "Rosemary": { spacing: 45, rows: null },
  "Sweet Basil": { spacing: 27, rows: null }, // 25-30cm -> average
  "Spicy Globe Basil": { spacing: 27, rows: null },
  "Blue Spice Bush Basil": { spacing: 27, rows: null },
  "Brussels Sprouts Flower Sprout": { spacing: 45, rows: null },
  "Superbunny Microdwarf Tomato": { spacing: null, rows: null },
  "Gunmetal Gray Dwarf Tomato": { spacing: null, rows: null },
  "Brown Sugar Tomato": { spacing: 75, rows: null },
  "Moonglow Jewel Tomato F2": { spacing: 60, rows: null },
  "White Tomesol Tomato": { spacing: 75, rows: null },
  "Blueberry Dessert Tomato": { spacing: null, rows: null },
  "Wolverine Tomato": { spacing: null, rows: null },
  "Candyland Tomato": { spacing: 75, rows: null },
  "Ground Cherry": { spacing: null, rows: null },
};

// Helper to get spacing for a seed
export function getSeedSpacing(seedName) {
  const data = SEED_SPACING[seedName];
  return data?.spacing || null;
}

// Helper to get rows for a seed
export function getSeedRows(seedName) {
  const data = SEED_SPACING[seedName];
  return data?.rows || 1;
}
